### ISSUE TITLE
Unable to add PDF file as attachement

### ISSUE THREAD

**Issue by ThomasVdBerge** [CleverIT/UBL_invoice#14]
I am trying to add a PHP file as attachement to my UBL document.

```
$pdfInvoice =  new \SplFileInfo('/tmp/test.pdf');
$additionalDocumentReference = new AdditionalDocumentReference();
$additionalDocumentReference->setFilename('test.pdf');
$additionalDocumentReference->setAttachment($pdfInvoice);
```

This however gives me the following error

> The writer cannot serialize objects of class: SplFileInfo

Which made me wonder, what type of input is expected for an attachement?

**Comment by baselbers** [comment]
The pdf file needs to be in binary code. Use `base64_encode()` and set it to the attachment element.
