### ISSUE TITLE
Multiple tax rates

### ISSUE THREAD

**Issue by hillelcoren** [CleverIT/UBL_invoice#2]
Is it possible to define multiple tax rates?

http://www.datypic.com/sc/ubl21/e-cac_TaxTotal.html

Thanks for the library!

**Comment by Stormyy** [comment]
Hi,

I just approved a pull request which makes this possible see https://github.com/CleverIT/UBL_invoice/pull/3

You can now add multiple TaxSubTotals so this makes it possible to have different tax rates

**Comment by hillelcoren** [comment]
That's awesome, thanks!
