### ISSUE TITLE
ErrorException in TaxTotal.php line 79:

### ISSUE THREAD

**Issue by hillelcoren** [CleverIT/UBL_invoice#4]
We're seeing the following error with the latest version:

ErrorException in TaxTotal.php line 79:
Undefined property: CleverIt\UBL\Invoice\TaxTotal::$taxSubTotal

This is the relevant line of code:

https://github.com/CleverIT/UBL_invoice/blob/master/src/classes/TaxTotal.php#L79

**Comment by Stormyy** [comment]
Hi

Oops made a mistake. Should be fixed in the new release (see https://github.com/CleverIT/UBL_invoice/releases/tag/v1.0.1).

**Comment by hillelcoren** [comment]
Great, thank you again!!
